name: segrag-paper
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12.12
  - pip
  - pytorch=2.7.0
  - torchvision=0.22.0
  - pytorch-cuda=12.6
  - numpy=2.2.6
  - pillow=11.3.0
  - pip:
    - ftfy==6.1.1
    - huggingface_hub
    - iopath>=0.1.10
    - lvis
    - omegaconf
    - pandas
    - pyarrow
    - pycocotools
    - PyYAML==6.0.3
    - regex
    - scikit-learn
    - submitit
    - termcolor
    - timm>=1.0.17
    - torchmetrics
    - tqdm
    - typing_extensions
